# O Básico do Numpy - Parte 1

O tutorial pode ser encontrado no <a href="https://www.linkedin.com/pulse/o-b%C3%A1sico-do-numpy-parte-1-geft%C3%A9-alcantara/?published=t">Linkedin</a>

In [2]:
#importando a biblioteca numpy
import numpy as np

## Criação de arrays 

In [5]:
#Covertendo uma lista python em um array 1D numpy
minha_lista = [1,2,3]
np.array(minha_lista)

array([1, 2, 3])

In [6]:
#convertendo uma lista de lista em um array 3D numpy (ou uma matriz 3X3)
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Um array numpy de 0 a 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Um array numpy de 0 a 10 com passo 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [46]:
#Gera uma matriz com três elementos zero
np.zeros(3)

array([0., 0., 0.])

In [47]:
#Gera uma matriz 5x5 com todos os elementos sendo zero
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
#Gera uma matriz com três elementos sendo 1
np.ones(3)

array([1., 1., 1.])

In [49]:
#Gera uma matriz 3x5 com todos os elementos sendo 1
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#Gera um vetor com uma saida de 2 elemento 
np.linspace(0,10,2)

array([ 0., 10.])

In [18]:
#Gera um vetor com uma saida de 10 elementos
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [19]:
#Gera uma matriz identidade 5X5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
identidade = np.eye(12)
print(identidade)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [21]:
#Matriz aleatória com distribuição uniforme
np.random.rand(9,2)

array([[0.06536057, 0.34397876],
       [0.35883058, 0.63091615],
       [0.73792446, 0.05594738],
       [0.46244558, 0.12383804],
       [0.79411843, 0.77664176],
       [0.16420955, 0.84971831],
       [0.68261069, 0.28878107],
       [0.77608291, 0.81277333],
       [0.68908289, 0.49381157]])

In [22]:
#Matriz com uma distribuição normal
np.random.randn(5)

array([-1.38668391, -1.71573816, -0.75421417,  0.14707266, -0.80089178])

In [23]:
#Matriz com inteiros aleatórios
np.random.randint(1,100,20)

array([47, 29, 18, 49, 37, 40, 19, 60, 72, 95, 79, 99, 57, 92, 65, 90, 50,
       36, 42, 64])

In [25]:
#Gerando um numero aleatório de 1 a 1000
np.random.randint(1,1000)

56

In [30]:
#arrays com numeros inteiros:
#Em sequência
array_1 = np.arange(56)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [31]:
#Aleatórios
array_2 = np.random.randint(0,120,10)
array_2

array([101,  46,  37,  95,  33,  96,  88,  51,  93,  19])

In [29]:
#Transformar o array_1 em uma matriz 8x7
array_1.reshape((8,7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55]])

In [32]:
#Devolve o maior valor do array_2
array_2.max()

101

In [33]:
#Retorna a posição do maior valor no array_2
array_2.argmax()

0

In [34]:
#Retorna o menor valor do array_2
array_2.min()

19

In [36]:
#Retorna a posição do menor valor do array_2
array_2.argmin()

9

In [37]:
#Retorna o tamanho do array_1
array_1.shape

(56,)

In [38]:
#Transforma o array 1 uma matriz de 1x56
array_1.reshape(1,56)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55]])

In [43]:
#Retorna o tamanho do array_1
array_1.reshape(1,56).shape

(1, 56)

In [40]:
#Transforma o array_1 em um array de 56x1
array_1.reshape(56,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55]])

In [41]:
#Retorna o tamanho do array_1
array_1.reshape(56,1).shape

(56, 1)

In [44]:
#Retorna o tipo de dado que o array_1 armazena
array_1.dtype

dtype('int32')